name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -warnaserror

      - name: Test
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx" --results-directory "TestResults"

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults/**/*.trx
          if-no-files-found: ignore
